# Generated by Django 5.2.1 on 2025-05-23 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditoriaVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('venta_id', models.IntegerField()),
                ('fecha_venta', models.DateField()),
                ('cliente_id', models.IntegerField()),
                ('empleado_id', models.IntegerField()),
                ('moto_id', models.IntegerField()),
                ('forma_pago', models.CharField(max_length=50)),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_eliminacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
